// Pulls the exact lucide paths the app imports out of node_modules, so the
// design files draw the same glyphs the app does.
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('../../', import.meta.url).pathname;
const SRC = join(ROOT, 'src');
const ICON_DIR = join(ROOT, 'node_modules/lucide-react-native/dist/esm/icons');

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (/\.(tsx?|mjs)$/.test(name)) out.push(full);
  }
  return out;
}

const names = new Set([
  // Always needed by the kit itself.
  'House', 'CreditCard', 'ReceiptText', 'Bolt', 'Bell', 'Plus', 'ChevronLeft', 'ChevronRight',
  'ChevronDown', 'Search', 'X', 'Check', 'Camera', 'ArrowDownLeft', 'ArrowUpRight', 'Calendar',
  'CalendarDays', 'CalendarPlus', 'Repeat', 'Banknote', 'Landmark', 'Users', 'TrendingUp',
  'FileText', 'Clock', 'Delete', 'Eye', 'EyeOff', 'Lock', 'Trash2', 'Pencil', 'Sparkles',
  'SlidersHorizontal', 'Filter', 'Wallet', 'PiggyBank', 'Percent', 'Info', 'Mail', 'Shield',
  'Sun', 'Moon', 'Smartphone', 'Palette', 'LogOut', 'UserPlus', 'UserRound', 'Settings',
  'GripVertical', 'ChevronUp', 'Minus', 'Star', 'Crown', 'Zap', 'RefreshCw', 'AlertCircle',
  'CircleAlert', 'Share', 'Copy', 'Image', 'ScanLine', 'Tag', 'Home', 'Car', 'Wifi', 'Droplets',
  'Flame', 'Phone', 'Tv', 'Dumbbell', 'HeartPulse', 'GraduationCap', 'ShoppingBag', 'Utensils',
  'Plane', 'Gift', 'Baby', 'PawPrint', 'Music', 'Gamepad2', 'Cloud', 'Briefcase', 'Bus',
  'Fuel', 'Stethoscope', 'Shirt', 'Coffee', 'Bike', 'Ticket', 'Book', 'HandCoins', 'Scale',
  'MessageCircle', 'HelpCircle', 'CircleHelp', 'Fingerprint', 'BellRing', 'Layers', 'LayoutGrid',
  'ArrowRight', 'ArrowLeft', 'Send', 'Handshake', 'Split', 'Receipt', 'CalendarClock',
]);

for (const file of walk(SRC)) {
  const text = readFileSync(file, 'utf8');
  for (const match of text.matchAll(/import\s*\{([^}]+)\}\s*from\s*'lucide-react-native'/g)) {
    for (const raw of match[1].split(',')) {
      const name = raw.replace(/\btype\b/, '').trim().split(/\s+as\s+/)[0];
      if (/^[A-Z][A-Za-z0-9]*$/.test(name)) names.add(name);
    }
  }
}

const kebab = (name) =>
  name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .replace(/([a-zA-Z])(\d)/g, '$1-$2')
    .toLowerCase();

// lucide 1.x renamed a few files; the app still imports the old names.
const ALIASES = { CircleHelp: 'circle-question-mark', HelpCircle: 'circle-question-mark', AlertCircle: 'circle-alert', Home: 'house', Filter: 'funnel' };

const icons = {};
const missing = [];
for (const name of [...names].sort()) {
  let text;
  try {
    text = readFileSync(join(ICON_DIR, `${ALIASES[name] ?? kebab(name)}.mjs`), 'utf8');
  } catch {
    missing.push(name);
    continue;
  }
  const start = text.indexOf('createLucideIcon(');
  const open = text.indexOf('[', start);
  const close = text.lastIndexOf(']);');
  const literal = text
    .slice(open, close + 1)
    .replace(/(\w+):\s/g, '"$1": ')
    .replace(/,\s*\]/g, ']')
    .replace(/,\s*\}/g, '}');
  const nodes = JSON.parse(literal);
  icons[name] = nodes.map(([tag, attrs]) => {
    const { key, ...rest } = attrs;
    return [tag, rest];
  });
}

writeFileSync(
  join(ROOT, 'design/kit/icons.mjs'),
  `// Generated by build-icons.mjs from lucide-react-native. Do not edit.\nexport const ICONS = ${JSON.stringify(icons)};\n`,
);
console.log(`${Object.keys(icons).length} icons written${missing.length ? `; missing: ${missing.join(', ')}` : ''}`);
