-- 0010 · Brand catalog seed
--
-- 293 US and Canadian retailers, restaurants and subscription
-- services. Generated, not hand-written — see scripts/gen-brands.mjs.
--
-- Re-running is safe: every row upserts on id, so editing a domain or a rank
-- and re-applying updates in place rather than duplicating.

insert into public.brands (id, name, domain, aliases, category_id, country, rank) values
  ('netflix', 'Netflix', 'netflix.com', array[]::text[], 'entertainment', 'both', 95),
  ('disney-plus', 'Disney+', 'disneyplus.com', array['disney plus', 'disney']::text[], 'entertainment', 'both', 85),
  ('hulu', 'Hulu', 'hulu.com', array[]::text[], 'entertainment', 'us', 80),
  ('hbo-max', 'HBO Max', 'hbomax.com', array['max', 'hbo']::text[], 'entertainment', 'us', 80),
  ('peacock', 'Peacock', 'peacocktv.com', array[]::text[], 'entertainment', 'us', 70),
  ('paramount-plus', 'Paramount+', 'paramountplus.com', array['paramount plus']::text[], 'entertainment', 'both', 70),
  ('sling-tv', 'Sling TV', 'sling.com', array[]::text[], 'entertainment', 'us', 55),
  ('fubo', 'Fubo', 'fubo.tv', array['fubotv']::text[], 'entertainment', 'both', 50),
  ('philo', 'Philo', 'philo.com', array[]::text[], 'entertainment', 'us', 40),
  ('starz', 'STARZ', 'starz.com', array[]::text[], 'entertainment', 'both', 50),
  ('amc-plus', 'AMC+', 'amcplus.com', array['amc plus']::text[], 'entertainment', 'both', 45),
  ('britbox', 'BritBox', 'britbox.com', array[]::text[], 'entertainment', 'both', 40),
  ('crunchyroll', 'Crunchyroll', 'crunchyroll.com', array[]::text[], 'entertainment', 'both', 55),
  ('discovery-plus', 'Discovery+', 'discoveryplus.com', array['discovery plus']::text[], 'entertainment', 'both', 50),
  ('espn-plus', 'ESPN+', 'espn.com', array['espn plus']::text[], 'entertainment', 'us', 60),
  ('dazn', 'DAZN', 'dazn.com', array[]::text[], 'entertainment', 'both', 45),
  ('crave', 'Crave', 'crave.ca', array[]::text[], 'entertainment', 'ca', 60),
  ('cbc-gem', 'CBC Gem', 'gem.cbc.ca', array['cbc gem premium', 'cbc gem']::text[], 'entertainment', 'ca', 45),
  ('stacktv', 'STACKTV', 'stacktv.ca', array['stack tv']::text[], 'entertainment', 'ca', 45),
  ('tsn-plus', 'TSN+', 'tsn.ca', array['tsn plus']::text[], 'entertainment', 'ca', 45),
  ('sportsnet-plus', 'Sportsnet+', 'sportsnet.ca', array['sportsnet plus']::text[], 'entertainment', 'ca', 45),
  ('illico-plus', 'illico+', 'illico.tv', array['illico']::text[], 'entertainment', 'ca', 30),
  ('hayu', 'Hayu', 'hayu.com', array[]::text[], 'entertainment', 'both', 30),
  ('spotify', 'Spotify', 'spotify.com', array[]::text[], 'entertainment', 'both', 95),
  ('youtube', 'YouTube', 'youtube.com', array['youtube premium', 'youtube tv', 'youtube music']::text[], 'entertainment', 'both', 80),
  ('siriusxm', 'SiriusXM', 'siriusxm.com', array['sirius']::text[], 'entertainment', 'both', 60),
  ('audible', 'Audible', 'audible.com', array[]::text[], 'news', 'both', 70),
  ('tidal', 'Tidal', 'tidal.com', array[]::text[], 'entertainment', 'both', 40),
  ('pandora', 'Pandora', 'pandora.com', array[]::text[], 'entertainment', 'us', 45),
  ('iheartradio', 'iHeartRadio', 'iheart.com', array['iheart']::text[], 'entertainment', 'both', 40),
  ('soundcloud', 'SoundCloud', 'soundcloud.com', array['soundcloud go+', 'soundcloud']::text[], 'entertainment', 'both', 35),
  ('pocket-casts', 'Pocket Casts', 'pocketcasts.com', array['pocket casts plus', 'pocket casts']::text[], 'entertainment', 'both', 25),
  ('xbox', 'Xbox', 'xbox.com', array['xbox game pass', 'game pass', 'xbox']::text[], 'entertainment', 'both', 75),
  ('playstation', 'PlayStation', 'playstation.com', array['playstation plus', 'ps plus', 'playstation']::text[], 'entertainment', 'both', 75),
  ('nintendo', 'Nintendo', 'nintendo.com', array['nintendo switch online', 'nintendo']::text[], 'entertainment', 'both', 70),
  ('ea', 'EA', 'ea.com', array['ea play']::text[], 'entertainment', 'both', 50),
  ('ubisoft', 'Ubisoft', 'ubisoft.com', array['ubisoft+', 'ubisoft plus']::text[], 'entertainment', 'both', 40),
  ('nvidia-geforce-now', 'NVIDIA GeForce NOW', 'nvidia.com', array['geforce now']::text[], 'entertainment', 'both', 40),
  ('roblox', 'Roblox', 'roblox.com', array['roblox premium', 'roblox']::text[], 'entertainment', 'both', 55),
  ('fortnite', 'Fortnite', 'fortnite.com', array['fortnite crew', 'fortnite']::text[], 'entertainment', 'both', 45),
  ('discord', 'Discord', 'discord.com', array['discord nitro', 'discord']::text[], 'entertainment', 'both', 55),
  ('google', 'Google', 'one.google.com', array['google one', 'google play pass']::text[], 'software', 'both', 75),
  ('microsoft', 'Microsoft', 'microsoft.com', array['microsoft 365', 'office 365', 'office']::text[], 'software', 'both', 75),
  ('dropbox', 'Dropbox', 'dropbox.com', array[]::text[], 'software', 'both', 60),
  ('adobe', 'Adobe', 'adobe.com', array['adobe creative cloud', 'adobe']::text[], 'software', 'both', 70),
  ('canva', 'Canva', 'canva.com', array['canva pro', 'canva']::text[], 'software', 'both', 65),
  ('notion', 'Notion', 'notion.so', array[]::text[], 'software', 'both', 55),
  ('evernote', 'Evernote', 'evernote.com', array[]::text[], 'software', 'both', 35),
  ('grammarly', 'Grammarly', 'grammarly.com', array[]::text[], 'software', 'both', 50),
  ('chatgpt', 'ChatGPT', 'openai.com', array['openai']::text[], 'software', 'both', 80),
  ('claude', 'Claude', 'claude.ai', array['anthropic']::text[], 'software', 'both', 70),
  ('github', 'GitHub', 'github.com', array[]::text[], 'software', 'both', 55),
  ('1password', '1Password', '1password.com', array['one password']::text[], 'software', 'both', 55),
  ('dashlane', 'Dashlane', 'dashlane.com', array[]::text[], 'software', 'both', 35),
  ('nordvpn', 'NordVPN', 'nordvpn.com', array['nord']::text[], 'software', 'both', 55),
  ('expressvpn', 'ExpressVPN', 'expressvpn.com', array['express vpn']::text[], 'software', 'both', 50),
  ('surfshark', 'Surfshark', 'surfshark.com', array[]::text[], 'software', 'both', 40),
  ('proton', 'Proton', 'proton.me', array['protonmail']::text[], 'software', 'both', 45),
  ('norton', 'Norton', 'norton.com', array[]::text[], 'software', 'both', 45),
  ('mcafee', 'McAfee', 'mcafee.com', array[]::text[], 'software', 'both', 45),
  ('malwarebytes', 'Malwarebytes', 'malwarebytes.com', array[]::text[], 'software', 'both', 35),
  ('zoom', 'Zoom', 'zoom.us', array[]::text[], 'software', 'both', 60),
  ('docusign', 'DocuSign', 'docusign.com', array[]::text[], 'software', 'both', 40),
  ('sam-s-club', 'Sam''s Club', 'samsclub.com', array['sams club']::text[], 'memberships', 'us', 65),
  ('instacart', 'Instacart', 'instacart.com', array['instacart+', 'instacart']::text[], 'memberships', 'both', 60),
  ('uber', 'Uber', 'uber.com', array['uber one', 'uber']::text[], 'memberships', 'both', 65),
  ('doordash', 'DoorDash', 'doordash.com', array['doordash dashpass', 'dashpass', 'doordash']::text[], 'memberships', 'both', 65),
  ('grubhub', 'Grubhub', 'grubhub.com', array['grubhub+', 'grubhub']::text[], 'memberships', 'us', 45),
  ('shipt', 'Shipt', 'shipt.com', array[]::text[], 'memberships', 'us', 40),
  ('pc-express', 'PC Express', 'pcexpress.ca', array['pc express pass', 'pc express']::text[], 'memberships', 'ca', 40),
  ('planet-fitness', 'Planet Fitness', 'planetfitness.com', array[]::text[], 'fitness', 'both', 75),
  ('la-fitness', 'LA Fitness', 'lafitness.com', array[]::text[], 'fitness', 'both', 60),
  ('anytime-fitness', 'Anytime Fitness', 'anytimefitness.com', array[]::text[], 'fitness', 'both', 60),
  ('ymca', 'YMCA', 'ymca.net', array[]::text[], 'fitness', 'both', 55),
  ('orangetheory', 'Orangetheory', 'orangetheory.com', array['orange theory']::text[], 'fitness', 'both', 50),
  ('crunch-fitness', 'Crunch Fitness', 'crunch.com', array['crunch']::text[], 'fitness', 'both', 45),
  ('equinox', 'Equinox', 'equinox.com', array[]::text[], 'fitness', 'both', 45),
  ('goodlife-fitness', 'GoodLife Fitness', 'goodlifefitness.com', array['goodlife']::text[], 'fitness', 'ca', 60),
  ('fit4less', 'Fit4Less', 'fit4less.ca', array['fit 4 less']::text[], 'fitness', 'ca', 45),
  ('f45', 'F45', 'f45training.com', array['f45 training']::text[], 'fitness', 'both', 40),
  ('peloton', 'Peloton', 'onepeloton.com', array[]::text[], 'fitness', 'both', 65),
  ('fitbit', 'Fitbit', 'fitbit.com', array['fitbit premium', 'fitbit']::text[], 'fitness', 'both', 45),
  ('strava', 'Strava', 'strava.com', array[]::text[], 'fitness', 'both', 50),
  ('classpass', 'ClassPass', 'classpass.com', array['class pass']::text[], 'fitness', 'both', 45),
  ('calm', 'Calm', 'calm.com', array[]::text[], 'fitness', 'both', 55),
  ('headspace', 'Headspace', 'headspace.com', array[]::text[], 'fitness', 'both', 55),
  ('myfitnesspal', 'MyFitnessPal', 'myfitnesspal.com', array['myfitnesspal premium', 'myfitnesspal']::text[], 'fitness', 'both', 50),
  ('noom', 'Noom', 'noom.com', array[]::text[], 'fitness', 'both', 45),
  ('the-new-york-times', 'The New York Times', 'nytimes.com', array['nyt', 'new york times']::text[], 'news', 'both', 75),
  ('the-wall-street-journal', 'The Wall Street Journal', 'wsj.com', array['wsj']::text[], 'news', 'both', 65),
  ('the-washington-post', 'The Washington Post', 'washingtonpost.com', array['wapo']::text[], 'news', 'us', 60),
  ('usa-today', 'USA Today', 'usatoday.com', array[]::text[], 'news', 'us', 45),
  ('the-athletic', 'The Athletic', 'theathletic.com', array['athletic']::text[], 'news', 'both', 45),
  ('the-globe-and-mail', 'The Globe and Mail', 'theglobeandmail.com', array['globe and mail']::text[], 'news', 'ca', 50),
  ('toronto-star', 'Toronto Star', 'thestar.com', array[]::text[], 'news', 'ca', 45),
  ('national-post', 'National Post', 'nationalpost.com', array[]::text[], 'news', 'ca', 45),
  ('financial-post', 'Financial Post', 'financialpost.com', array[]::text[], 'news', 'ca', 35),
  ('everand', 'Everand', 'everand.com', array['scribd']::text[], 'news', 'both', 30),
  ('medium', 'Medium', 'medium.com', array[]::text[], 'news', 'both', 40),
  ('substack', 'Substack', 'substack.com', array[]::text[], 'news', 'both', 45),
  ('coursera', 'Coursera', 'coursera.org', array['coursera plus', 'coursera']::text[], 'news', 'both', 45),
  ('masterclass', 'MasterClass', 'masterclass.com', array['master class']::text[], 'news', 'both', 45),
  ('linkedin', 'LinkedIn', 'linkedin.com', array['linkedin premium', 'linkedin']::text[], 'news', 'both', 55),
  ('duolingo', 'Duolingo', 'duolingo.com', array[]::text[], 'news', 'both', 60),
  ('chegg', 'Chegg', 'chegg.com', array[]::text[], 'news', 'both', 40),
  ('hellofresh', 'HelloFresh', 'hellofresh.com', array['hello fresh']::text[], 'meals', 'both', 70),
  ('factor', 'Factor', 'factor75.com', array['factor 75']::text[], 'meals', 'both', 50),
  ('home-chef', 'Home Chef', 'homechef.com', array[]::text[], 'meals', 'us', 50),
  ('everyplate', 'EveryPlate', 'everyplate.com', array['every plate']::text[], 'meals', 'both', 45),
  ('green-chef', 'Green Chef', 'greenchef.com', array[]::text[], 'meals', 'both', 40),
  ('blue-apron', 'Blue Apron', 'blueapron.com', array[]::text[], 'meals', 'us', 45),
  ('hungryroot', 'Hungryroot', 'hungryroot.com', array[]::text[], 'meals', 'us', 40),
  ('cookunity', 'CookUnity', 'cookunity.com', array['cook unity']::text[], 'meals', 'us', 35),
  ('chef-s-plate', 'Chef''s Plate', 'chefsplate.com', array['chefs plate']::text[], 'meals', 'ca', 45),
  ('goodfood', 'Goodfood', 'makegoodfood.ca', array['good food']::text[], 'meals', 'ca', 45),
  ('fresh-prep', 'Fresh Prep', 'freshprep.ca', array[]::text[], 'meals', 'ca', 35),
  ('tinder', 'Tinder', 'tinder.com', array[]::text[], 'software', 'both', 60),
  ('bumble', 'Bumble', 'bumble.com', array[]::text[], 'software', 'both', 55),
  ('hinge', 'Hinge', 'hinge.co', array[]::text[], 'software', 'both', 55),
  ('match', 'Match', 'match.com', array[]::text[], 'software', 'both', 40),
  ('eharmony', 'eHarmony', 'eharmony.com', array['e harmony']::text[], 'software', 'both', 35),
  ('snapchat', 'Snapchat', 'snapchat.com', array['snapchat+', 'snapchat']::text[], 'software', 'both', 55),
  ('reddit', 'Reddit', 'reddit.com', array['reddit premium', 'reddit']::text[], 'software', 'both', 50),
  ('x', 'X', 'x.com', array['x premium', 'twitter blue', 'twitter']::text[], 'software', 'both', 50),
  ('aaa', 'AAA', 'aaa.com', array['triple a']::text[], 'transport', 'us', 65),
  ('caa', 'CAA', 'caa.ca', array[]::text[], 'transport', 'ca', 60),
  ('onstar', 'OnStar', 'onstar.com', array['on star']::text[], 'transport', 'both', 45),
  ('tesla', 'Tesla', 'tesla.com', array['tesla premium connectivity', 'tesla']::text[], 'transport', 'both', 45),
  ('ring', 'Ring', 'ring.com', array['ring protect', 'ring']::text[], 'home', 'both', 55),
  ('nest', 'Nest', 'nest.com', array['nest aware', 'nest']::text[], 'home', 'both', 50),
  ('arlo', 'Arlo', 'arlo.com', array['arlo secure', 'arlo']::text[], 'home', 'both', 40),
  ('simplisafe', 'SimpliSafe', 'simplisafe.com', array['simpli safe']::text[], 'home', 'both', 45),
  ('adt', 'ADT', 'adt.com', array[]::text[], 'home', 'both', 50),
  ('barkbox', 'BarkBox', 'barkbox.com', array['bark box']::text[], 'pets', 'both', 45),
  ('amazon', 'Amazon', 'amazon.com', array['amzn', 'amazon.ca', 'amazon music unlimited', 'amazon music', 'amazon prime', 'prime', 'kindle unlimited', 'kindle', 'amazon prime video', 'prime video']::text[], 'shopping', 'both', 99),
  ('walmart', 'Walmart', 'walmart.com', array['wal mart', 'wm supercenter', 'walmart+', 'walmart plus', 'walmart pharmacy']::text[], 'shopping', 'both', 98),
  ('costco', 'Costco', 'costco.com', array['costco membership', 'costco pharmacy']::text[], 'shopping', 'both', 95),
  ('target', 'Target', 'target.com', array[]::text[], 'shopping', 'us', 92),
  ('ebay', 'eBay', 'ebay.com', array[]::text[], 'shopping', 'both', 65),
  ('etsy', 'Etsy', 'etsy.com', array[]::text[], 'shopping', 'both', 60),
  ('temu', 'Temu', 'temu.com', array[]::text[], 'shopping', 'both', 60),
  ('shein', 'SHEIN', 'shein.com', array[]::text[], 'clothing', 'both', 60),
  ('aliexpress', 'AliExpress', 'aliexpress.com', array['ali express']::text[], 'shopping', 'both', 45),
  ('dollar-general', 'Dollar General', 'dollargeneral.com', array[]::text[], 'shopping', 'us', 70),
  ('dollar-tree', 'Dollar Tree', 'dollartree.com', array[]::text[], 'shopping', 'both', 65),
  ('five-below', 'Five Below', 'fivebelow.com', array[]::text[], 'shopping', 'us', 50),
  ('canadian-tire', 'Canadian Tire', 'canadiantire.ca', array['canadian tire gas', 'ct gas']::text[], 'shopping', 'ca', 80),
  ('giant-tiger', 'Giant Tiger', 'gianttiger.com', array[]::text[], 'shopping', 'ca', 55),
  ('dollarama', 'Dollarama', 'dollarama.com', array[]::text[], 'shopping', 'ca', 75),
  ('kroger', 'Kroger', 'kroger.com', array['kroger pharmacy']::text[], 'groceries', 'us', 85),
  ('albertsons', 'Albertsons', 'albertsons.com', array[]::text[], 'groceries', 'us', 70),
  ('safeway', 'Safeway', 'safeway.com', array['safeway canada']::text[], 'groceries', 'both', 75),
  ('publix', 'Publix', 'publix.com', array['publix pharmacy']::text[], 'groceries', 'us', 80),
  ('aldi', 'Aldi', 'aldi.us', array[]::text[], 'groceries', 'both', 80),
  ('trader-joe-s', 'Trader Joe''s', 'traderjoes.com', array['trader joes']::text[], 'groceries', 'us', 80),
  ('whole-foods-market', 'Whole Foods Market', 'wholefoodsmarket.com', array['whole foods']::text[], 'groceries', 'both', 80),
  ('h-e-b', 'H-E-B', 'heb.com', array['heb']::text[], 'groceries', 'us', 70),
  ('meijer', 'Meijer', 'meijer.com', array[]::text[], 'groceries', 'us', 65),
  ('wegmans', 'Wegmans', 'wegmans.com', array[]::text[], 'groceries', 'us', 65),
  ('food-lion', 'Food Lion', 'foodlion.com', array[]::text[], 'groceries', 'us', 60),
  ('stop-and-shop', 'Stop & Shop', 'stopandshop.com', array['stop and shop']::text[], 'groceries', 'us', 60),
  ('giant-food', 'Giant Food', 'giantfood.com', array[]::text[], 'groceries', 'us', 55),
  ('giant-eagle', 'Giant Eagle', 'gianteagle.com', array[]::text[], 'groceries', 'us', 55),
  ('shoprite', 'ShopRite', 'shoprite.com', array['shop rite']::text[], 'groceries', 'us', 60),
  ('winco-foods', 'WinCo Foods', 'wincofoods.com', array['winco']::text[], 'groceries', 'us', 50),
  ('sprouts-farmers-market', 'Sprouts Farmers Market', 'sprouts.com', array['sprouts']::text[], 'groceries', 'us', 55),
  ('hy-vee', 'Hy-Vee', 'hy-vee.com', array['hyvee']::text[], 'groceries', 'us', 55),
  ('harris-teeter', 'Harris Teeter', 'harristeeter.com', array[]::text[], 'groceries', 'us', 55),
  ('ralphs', 'Ralphs', 'ralphs.com', array[]::text[], 'groceries', 'us', 55),
  ('fred-meyer', 'Fred Meyer', 'fredmeyer.com', array[]::text[], 'groceries', 'us', 55),
  ('smith-s', 'Smith''s', 'smithsfoodanddrug.com', array['smiths']::text[], 'groceries', 'us', 45),
  ('mariano-s', 'Mariano''s', 'marianos.com', array['marianos']::text[], 'groceries', 'us', 45),
  ('qfc', 'QFC', 'qfc.com', array[]::text[], 'groceries', 'us', 40),
  ('jewel-osco', 'Jewel-Osco', 'jewelosco.com', array['jewel osco']::text[], 'groceries', 'us', 50),
  ('vons', 'Vons', 'vons.com', array[]::text[], 'groceries', 'us', 50),
  ('piggly-wiggly', 'Piggly Wiggly', 'pigglywiggly.com', array[]::text[], 'groceries', 'us', 35),
  ('loblaws', 'Loblaws', 'loblaws.ca', array[]::text[], 'groceries', 'ca', 85),
  ('no-frills', 'No Frills', 'nofrills.ca', array['nofrills']::text[], 'groceries', 'ca', 85),
  ('real-canadian-superstore', 'Real Canadian Superstore', 'realcanadiansuperstore.ca', array['superstore']::text[], 'groceries', 'ca', 80),
  ('your-independent-grocer', 'Your Independent Grocer', 'yourindependentgrocer.ca', array['independent']::text[], 'groceries', 'ca', 55),
  ('zehrs', 'Zehrs', 'zehrs.ca', array[]::text[], 'groceries', 'ca', 55),
  ('fortinos', 'Fortinos', 'fortinos.ca', array[]::text[], 'groceries', 'ca', 50),
  ('provigo', 'Provigo', 'provigo.ca', array[]::text[], 'groceries', 'ca', 55),
  ('maxi', 'Maxi', 'maxi.ca', array[]::text[], 'groceries', 'ca', 55),
  ('atlantic-superstore', 'Atlantic Superstore', 'atlanticsuperstore.ca', array[]::text[], 'groceries', 'ca', 45),
  ('t-and-t-supermarket', 'T&T Supermarket', 'tntsupermarket.com', array['t and t']::text[], 'groceries', 'ca', 55),
  ('sobeys', 'Sobeys', 'sobeys.com', array[]::text[], 'groceries', 'ca', 80),
  ('freshco', 'FreshCo', 'freshco.com', array['fresh co']::text[], 'groceries', 'ca', 70),
  ('foodland', 'Foodland', 'foodland.ca', array[]::text[], 'groceries', 'ca', 50),
  ('farm-boy', 'Farm Boy', 'farmboy.ca', array[]::text[], 'groceries', 'ca', 55),
  ('iga', 'IGA', 'iga.net', array[]::text[], 'groceries', 'ca', 60),
  ('metro', 'Metro', 'metro.ca', array[]::text[], 'groceries', 'ca', 75),
  ('food-basics', 'Food Basics', 'foodbasics.ca', array[]::text[], 'groceries', 'ca', 65),
  ('super-c', 'Super C', 'superc.ca', array[]::text[], 'groceries', 'ca', 55),
  ('longo-s', 'Longo''s', 'longos.com', array['longos']::text[], 'groceries', 'ca', 50),
  ('save-on-foods', 'Save-On-Foods', 'saveonfoods.com', array['save on foods']::text[], 'groceries', 'ca', 65),
  ('pricesmart-foods', 'PriceSmart Foods', 'pricesmartfoods.ca', array[]::text[], 'groceries', 'ca', 35),
  ('urban-fare', 'Urban Fare', 'urbanfare.com', array[]::text[], 'groceries', 'ca', 30),
  ('thrifty-foods', 'Thrifty Foods', 'thriftyfoods.com', array[]::text[], 'groceries', 'ca', 45),
  ('co-op', 'Co-op', 'crs.coop', array['coop']::text[], 'groceries', 'ca', 45),
  ('calgary-co-op', 'Calgary Co-op', 'calgarycoop.com', array['calgary coop']::text[], 'groceries', 'ca', 40),
  ('northmart', 'NorthMart', 'northmart.ca', array['north mart']::text[], 'groceries', 'ca', 25),
  ('cvs', 'CVS', 'cvs.com', array['cvs pharmacy']::text[], 'pharmacy', 'us', 85),
  ('walgreens', 'Walgreens', 'walgreens.com', array[]::text[], 'pharmacy', 'us', 85),
  ('shoppers-drug-mart', 'Shoppers Drug Mart', 'shoppersdrugmart.ca', array['shoppers']::text[], 'pharmacy', 'ca', 85),
  ('rexall', 'Rexall', 'rexall.ca', array[]::text[], 'pharmacy', 'ca', 65),
  ('jean-coutu', 'Jean Coutu', 'jeancoutu.com', array[]::text[], 'pharmacy', 'ca', 60),
  ('pharmasave', 'Pharmasave', 'pharmasave.com', array[]::text[], 'pharmacy', 'ca', 45),
  ('london-drugs', 'London Drugs', 'londondrugs.com', array[]::text[], 'pharmacy', 'ca', 55),
  ('the-home-depot', 'The Home Depot', 'homedepot.com', array['home depot']::text[], 'home', 'both', 90),
  ('lowe-s', 'Lowe''s', 'lowes.com', array['lowes']::text[], 'home', 'both', 85),
  ('ace-hardware', 'Ace Hardware', 'acehardware.com', array['ace']::text[], 'home', 'both', 60),
  ('menards', 'Menards', 'menards.com', array[]::text[], 'home', 'us', 60),
  ('harbor-freight', 'Harbor Freight', 'harborfreight.com', array[]::text[], 'home', 'us', 55),
  ('tractor-supply', 'Tractor Supply', 'tractorsupply.com', array[]::text[], 'home', 'us', 55),
  ('rona', 'RONA', 'rona.ca', array[]::text[], 'home', 'ca', 65),
  ('home-hardware', 'Home Hardware', 'homehardware.ca', array[]::text[], 'home', 'ca', 60),
  ('ikea', 'IKEA', 'ikea.com', array[]::text[], 'home', 'both', 75),
  ('wayfair', 'Wayfair', 'wayfair.com', array[]::text[], 'home', 'both', 60),
  ('homesense', 'HomeSense', 'homesense.com', array['home sense']::text[], 'home', 'both', 55),
  ('bed-bath-and-beyond', 'Bed Bath & Beyond', 'bedbathandbeyond.com', array['bed bath and beyond']::text[], 'home', 'both', 45),
  ('macy-s', 'Macy''s', 'macys.com', array['macys']::text[], 'clothing', 'us', 70),
  ('nordstrom', 'Nordstrom', 'nordstrom.com', array[]::text[], 'clothing', 'both', 60),
  ('kohl-s', 'Kohl''s', 'kohls.com', array['kohls']::text[], 'clothing', 'us', 65),
  ('jcpenney', 'JCPenney', 'jcpenney.com', array['jc penney']::text[], 'clothing', 'us', 50),
  ('old-navy', 'Old Navy', 'oldnavy.com', array[]::text[], 'clothing', 'both', 70),
  ('gap', 'Gap', 'gap.com', array[]::text[], 'clothing', 'both', 60),
  ('banana-republic', 'Banana Republic', 'bananarepublic.com', array[]::text[], 'clothing', 'both', 50),
  ('h-and-m', 'H&M', 'hm.com', array['h and m', 'hm']::text[], 'clothing', 'both', 70),
  ('zara', 'Zara', 'zara.com', array[]::text[], 'clothing', 'both', 70),
  ('uniqlo', 'Uniqlo', 'uniqlo.com', array[]::text[], 'clothing', 'both', 60),
  ('tj-maxx', 'TJ Maxx', 'tjmaxx.com', array['tjmaxx']::text[], 'clothing', 'us', 70),
  ('marshalls', 'Marshalls', 'marshalls.com', array[]::text[], 'clothing', 'both', 65),
  ('ross', 'Ross', 'rossstores.com', array['ross dress for less']::text[], 'clothing', 'us', 65),
  ('burlington', 'Burlington', 'burlington.com', array[]::text[], 'clothing', 'us', 55),
  ('winners', 'Winners', 'winners.ca', array[]::text[], 'clothing', 'ca', 70),
  ('aritzia', 'Aritzia', 'aritzia.com', array[]::text[], 'clothing', 'ca', 60),
  ('lululemon', 'Lululemon', 'lululemon.com', array['lulu']::text[], 'clothing', 'both', 70),
  ('nike', 'Nike', 'nike.com', array[]::text[], 'clothing', 'both', 80),
  ('adidas', 'Adidas', 'adidas.com', array[]::text[], 'clothing', 'both', 70),
  ('foot-locker', 'Foot Locker', 'footlocker.com', array[]::text[], 'clothing', 'both', 55),
  ('levi-s', 'Levi''s', 'levi.com', array['levis']::text[], 'clothing', 'both', 55),
  ('best-buy', 'Best Buy', 'bestbuy.com', array['bestbuy']::text[], 'electronics', 'both', 85),
  ('apple', 'Apple', 'apple.com', array['apple store', 'apple', 'apple tv+', 'apple tv plus', 'apple music', 'apple podcasts', 'apple arcade', 'icloud+', 'icloud', 'apple fitness+', 'apple fitness plus', 'apple news+', 'apple news plus']::text[], 'electronics', 'both', 85),
  ('staples', 'Staples', 'staples.com', array[]::text[], 'electronics', 'both', 65),
  ('gamestop', 'GameStop', 'gamestop.com', array['game stop']::text[], 'electronics', 'both', 55),
  ('micro-center', 'Micro Center', 'microcenter.com', array[]::text[], 'electronics', 'us', 50),
  ('canada-computers', 'Canada Computers', 'canadacomputers.com', array[]::text[], 'electronics', 'ca', 45),
  ('memory-express', 'Memory Express', 'memoryexpress.com', array[]::text[], 'electronics', 'ca', 40),
  ('sephora', 'Sephora', 'sephora.com', array[]::text[], 'beauty', 'both', 75),
  ('ulta-beauty', 'Ulta Beauty', 'ulta.com', array['ulta']::text[], 'beauty', 'us', 70),
  ('bath-and-body-works', 'Bath & Body Works', 'bathandbodyworks.com', array['bath and body works']::text[], 'beauty', 'both', 60),
  ('sally-beauty', 'Sally Beauty', 'sallybeauty.com', array[]::text[], 'beauty', 'both', 45),
  ('lush', 'Lush', 'lush.com', array[]::text[], 'beauty', 'both', 50),
  ('mac-cosmetics', 'MAC Cosmetics', 'maccosmetics.com', array['mac']::text[], 'beauty', 'both', 50),
  ('petsmart', 'PetSmart', 'petsmart.com', array['pet smart']::text[], 'pets', 'both', 70),
  ('petco', 'Petco', 'petco.com', array['petco vital care', 'vital care']::text[], 'pets', 'us', 65),
  ('chewy', 'Chewy', 'chewy.com', array[]::text[], 'pets', 'us', 65),
  ('pet-valu', 'Pet Valu', 'petvalu.ca', array['petvalu']::text[], 'pets', 'ca', 55),
  ('ren-s-pets', 'Ren''s Pets', 'renspets.com', array['rens pets']::text[], 'pets', 'ca', 40),
  ('global-pet-foods', 'Global Pet Foods', 'globalpetfoods.com', array[]::text[], 'pets', 'ca', 35),
  ('7-eleven', '7-Eleven', '7-eleven.com', array['7 eleven', 'seven eleven']::text[], 'fuel', 'both', 80),
  ('circle-k', 'Circle K', 'circlek.com', array[]::text[], 'fuel', 'both', 75),
  ('shell', 'Shell', 'shell.com', array[]::text[], 'fuel', 'both', 85),
  ('exxon', 'Exxon', 'exxon.com', array[]::text[], 'fuel', 'us', 75),
  ('mobil', 'Mobil', 'mobil.com', array['exxonmobil']::text[], 'fuel', 'us', 70),
  ('chevron', 'Chevron', 'chevron.com', array[]::text[], 'fuel', 'us', 75),
  ('bp', 'BP', 'bp.com', array[]::text[], 'fuel', 'both', 70),
  ('sunoco', 'Sunoco', 'sunoco.com', array[]::text[], 'fuel', 'us', 55),
  ('speedway', 'Speedway', 'speedway.com', array[]::text[], 'fuel', 'us', 55),
  ('wawa', 'Wawa', 'wawa.com', array[]::text[], 'fuel', 'us', 60),
  ('sheetz', 'Sheetz', 'sheetz.com', array[]::text[], 'fuel', 'us', 55),
  ('quiktrip', 'QuikTrip', 'quiktrip.com', array['qt']::text[], 'fuel', 'us', 55),
  ('casey-s', 'Casey''s', 'caseys.com', array['caseys']::text[], 'fuel', 'us', 50),
  ('petro-canada', 'Petro-Canada', 'petro-canada.ca', array['petro canada']::text[], 'fuel', 'ca', 75),
  ('esso', 'Esso', 'esso.ca', array[]::text[], 'fuel', 'ca', 75),
  ('irving', 'Irving', 'irvingoil.com', array['irving oil']::text[], 'fuel', 'ca', 55),
  ('mcdonald-s', 'McDonald''s', 'mcdonalds.com', array['mcdonalds', 'mc donalds', 'mcd']::text[], 'dining', 'both', 95),
  ('starbucks', 'Starbucks', 'starbucks.com', array[]::text[], 'dining', 'both', 95),
  ('subway', 'Subway', 'subway.com', array[]::text[], 'dining', 'both', 80),
  ('tim-hortons', 'Tim Hortons', 'timhortons.com', array['tims', 'tim horton']::text[], 'dining', 'ca', 92),
  ('dunkin', 'Dunkin''', 'dunkindonuts.com', array['dunkin', 'dunkin donuts']::text[], 'dining', 'us', 80),
  ('taco-bell', 'Taco Bell', 'tacobell.com', array[]::text[], 'dining', 'both', 80),
  ('chick-fil-a', 'Chick-fil-A', 'chick-fil-a.com', array['chick fil a', 'chickfila']::text[], 'dining', 'us', 85),
  ('wendy-s', 'Wendy''s', 'wendys.com', array['wendys']::text[], 'dining', 'both', 80),
  ('burger-king', 'Burger King', 'bk.com', array['bk']::text[], 'dining', 'both', 80),
  ('chipotle', 'Chipotle', 'chipotle.com', array[]::text[], 'dining', 'both', 80),
  ('domino-s', 'Domino''s', 'dominos.com', array['dominos']::text[], 'dining', 'both', 75),
  ('pizza-hut', 'Pizza Hut', 'pizzahut.com', array[]::text[], 'dining', 'both', 70),
  ('kfc', 'KFC', 'kfc.com', array['kentucky fried chicken']::text[], 'dining', 'both', 75),
  ('popeyes', 'Popeyes', 'popeyes.com', array[]::text[], 'dining', 'both', 70),
  ('panera-bread', 'Panera Bread', 'panerabread.com', array['panera']::text[], 'dining', 'us', 65),
  ('a-and-w', 'A&W', 'aw.com', array['a and w']::text[], 'dining', 'both', 65)
on conflict (id) do update
  set name        = excluded.name,
      domain      = excluded.domain,
      aliases     = excluded.aliases,
      category_id = excluded.category_id,
      country     = excluded.country,
      rank        = excluded.rank;
